language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - srecord
      - gcovr

before_install:
  - pip install --user cpp-coveralls

install:
  - ./autogen.sh
  - ./configure --enable-gcov

script: 
  - make
  - make firmware_tool
  - make server
  - make assets
  - ./utils/server/server -f assets/slot_d.bin >/dev/null 2>&1 &
  - make clean # This is needed since the library has been build before without coverage support
  - make check

after_success:
  - coveralls -e test -e ext -e /usr -e utils -e build -i src -b test -r . --gcov-options '\-lp'
